mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include('register.urls')) # register の urls.py に遷移

]

register/urls.py
from django.urls import path
from . import views
from scalendar import views as s_views 
app_name = 'register'

urlpatterns = [

    path('', views.Top.as_view(), name='top'), # register の view.py の class Top を参照
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done/', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('mycalendar/', views.MyCalendar.as_view(), name='mycalendar'),
    path('mycalendar/delete/<int:id>', s_views.delete, name='delete'),
    path('mycalendar/<int:year>/<int:month>/<int:day>/', views.MyCalendar.as_view(), name='mycalendar'),
    path('month_with_schedule/',views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'),
    path('month_with_schedule/',views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'),
    path('month_with_schedule/<int:year>/<int:month>/',views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'),
    path('month_with_schedule/delete/<int:id>', s_views.delete_m, name='delete_m'),
    path('management/', views.Management.as_view(), name='management'),
    path('management/decision_numbers/', views.DecisionNumbers.as_view(), name='decision_numbers'),
    path('management/mail/', views.Mail.as_view(), name='mail'),
    path('management/mail/<int:year>/<int:month>/<int:day>/', views.Mail.as_view(), name='mail'),
    path(
        'month_with_forms/',
        views.MonthWithFormsCalendar.as_view(), name='month_with_forms'
    ),
    path(
        'month_with_forms/<int:year>/<int:month>/',
        views.MonthWithFormsCalendar.as_view(), name='month_with_forms'
    ),
    
    path('staff_index/', views.StaffIndex.as_view(), name='staff_index'),
    path('staff_delete/<int:pk>', views.StaffDelete.as_view(), name='staff_delete'),
   

]

scalendar/models.py
import datetime
from django.db import models
from django.utils import timezone


class Schedule(models.Model):
    """スケジュール"""
    user_name = models.CharField('登録者', max_length=150)
    summary = models.CharField('備考', max_length=50, blank=True)
    start_time = models.TimeField('開始時間', default=datetime.time(7, 0, 0))
    night_start_time = models.TimeField('夜シフト開始時間', default=datetime.time(17, 0, 0))
    end_time = models.TimeField('終了時間', default=datetime.time(7, 0, 0))
    date = models.DateField('日付')
    created_at = models.DateTimeField('作成日', default=timezone.now)
    noon_numbers = models.IntegerField('昼シフト人数', default=0, blank=True)
    night_numbers = models.IntegerField('夜シフト人数', default=0, blank=True)

    # created_at = models.DateTimeField('作成日', default=timezone.now)
    # noon_numbers = models.IntegerField('昼シフト人数', default=0, blank=True)
    # night_numbers = models.IntegerField('夜シフト人数', default=0, blank=True)


    def __str__(self):
        return self.summary

class Decision(models.Model):
    date = models.DateField('日付')
    noon_numbers = models.IntegerField('昼シフト人数', default=0, blank=True)
    night_numbers = models.IntegerField('夜シフト人数', default=0, blank=True)

    def __str__(self):
        return models.Model.__str__(self)

register/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm, UserCreationForm, PasswordChangeForm,
    PasswordResetForm, SetPasswordForm
)
from django.contrib.auth import get_user_model

User = get_user_model()

from .models import EmailText

class LoginForm(AuthenticationForm):
    """ログインフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label  # placeholder にフィールドのラベルを入れる


class UserCreateForm(UserCreationForm):
    """ユーザー登録用フォーム"""

    class Meta:
        model = User
        if User.USERNAME_FIELD == 'email':
            fields = ('email',)
        else:
            fields = ('username', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class UserUpdateForm(forms.ModelForm):
    """ユーザー情報更新フォーム"""

    class Meta:
        model = User
        if User.USERNAME_FIELD == 'email':
            fields = ('email', 'first_name', 'last_name')
        else:
            fields = ('username', 'email', 'first_name', 'last_name')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class MyPasswordChangeForm(PasswordChangeForm):
    """パスワード変更フォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MyPasswordResetForm(PasswordResetForm):
    """パスワード忘れたときのフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MySetPasswordForm(SetPasswordForm):
    """パスワード再設定用フォーム(パスワード忘れて再設定)"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class EmailTextForm(forms.ModelForm):
    """Bootstrapに対応するためのModelForm"""

    class Meta:
        model = EmailText
        fields = ('summary', 'description')
        widgets = {
            'summary': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
            }),
        }

register/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
    )
from django.contrib.sites.shortcuts import get_current_site
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.http import HttpResponseBadRequest
from django.shortcuts import redirect, render, resolve_url
from django.template.loader import get_template
from django.urls import reverse_lazy
from django.views import generic
from .forms import (
    LoginForm, UserCreateForm, UserUpdateForm, MyPasswordChangeForm,
    MyPasswordResetForm, MySetPasswordForm, EmailTextForm
)
from scalendar.views import (
    MonthCalendarMixin, WeekCalendarMixin,
    WeekWithScheduleMixin, MonthWithScheduleMixin
)
import datetime
import calendar
from django.shortcuts import redirect
from django.views import generic
from scalendar.forms import BS4ScheduleForm, SimpleScheduleForm
from scalendar.forms import BS4ScheduleForm
from django.contrib.auth.models import User
from django.shortcuts import render

from django.core.mail import EmailMessage
from django.http import HttpResponse
from register import mixins
from scalendar.models import Schedule, Decision
# Create your views here.


User = get_user_model()

class Top(generic.TemplateView):
    template_name = 'register/top.html' # register の top.html を参照


class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm # register の forms.py の LoginForm を設ける
    template_name = 'register/login.html'


class Logout(LoginRequiredMixin, LogoutView):
    """ログアウトページ"""
    template_name = 'register/top.html'


class UserCreate(generic.CreateView):
    """ユーザー仮登録"""
    template_name = 'register/user_create.html'
    form_class = UserCreateForm

    def form_valid(self, form):
        """仮登録と本登録用メールの発行."""
        # 仮登録と本登録の切り替えは、is_active属性を使うと簡単です。
        # 退会処理も、is_activeをFalseにするだけにしておくと捗ります。
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': 'https' if self.request.is_secure() else 'http',
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }

        subject_template = get_template('register/mail_template/create/subject.txt')
        subject = subject_template.render(context)

        message_template = get_template('register/mail_template/create/message.txt')
        message = message_template.render(context)

        user.email_user(subject, message)
        return redirect('register:user_create_done')


class UserCreateDone(generic.TemplateView):
    """ユーザー仮登録したよ"""
    template_name = 'register/user_create_done.html'


class UserCreateComplete(generic.TemplateView):
    """メール内URLアクセス後のユーザー本登録"""
    template_name = 'register/user_create_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        """tokenが正しければ本登録."""
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoenNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # まだ仮登録で、他に問題なければ本登録とする
                    user.is_active = True
                    user.save()
                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()

class OnlyYouMixin(UserPassesTestMixin):
    """本人か、スーパーユーザーだけユーザーページアクセスを許可する"""
    raise_exception = True

    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser

class OnlySuperuser(UserPassesTestMixin):
    """UserPassesTestMixin ログインし、特定のユーザにのみ表示を行なう"""
    """スーパーユーザーだけに閲覧を許可する"""
    raise_exception = True

    def test_func(self):
        user = self.request.user
        return user.is_superuser

class Management(OnlySuperuser, generic.TemplateView):
    '''管理者の専用ページ'''
    model = User
    template_name = 'register/management.html'

class DecisionNumbers(OnlySuperuser, generic.TemplateView):
    '''シフトの人数の調整ページ'''
    model = User
    template_name = 'register/decision_numbers.html'

class MonthWithFormsCalendar(mixins.MonthWithFormsMixin, generic.View):
    """フォーム付きの月間カレンダーを表示するビュー"""
    template_name='register/month_with_forms.html'
    model = Decision
    date_field = 'date'
    form_class = SimpleScheduleForm

    def get(self, request, **kwargs):
        context = self.get_month_calendar()
        # last_date = calendar.monthrange(context['month']['current'].year, context['month']['current'].month)[1]

        return render(request, self.template_name, context)

    def post(self, request, **kwargs):
        context = self.get_month_calendar()
        formset = context['month_formset']
        if formset.is_valid():
            formset.save()
            return redirect('register:month_with_forms')

        return render(request, self.template_name, context)


class Mail(OnlySuperuser, MonthCalendarMixin, WeekWithScheduleMixin, generic.CreateView):
    '''メール送信ページ'''
    model = User
    template_name = 'register/mail.html'

    form_class = EmailTextForm

    def get_context_data(self, **kwargs):
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        day = self.kwargs.get('day')
        if month and year and day:
            date = datetime.date(year=int(year), month=int(month), day=int(day))
        else:
            date = datetime.date.today()

        context = super().get_context_data(**kwargs)
        context['week'] = self.get_week_calendar()
        context['month'] = self.get_month_calendar()
        context['selected_date'] = date
        return context

    def form_valid(self, form):
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        day = self.kwargs.get('day')
        if month and year and day:
            date = datetime.date(year=int(year), month=int(month), day=int(day))
        else:
            date = datetime.date.today()
        schedule = form.save(commit=False)
        schedule.date = date
        for staff in User.objects.all():
            EmailMessage('緊急メール:' + str(schedule.date), schedule.description + '', to = [staff.email]).send()
        return redirect('register:mail', year=date.year, month=date.month, day=date.day)


class StaffIndex(OnlySuperuser,generic.TemplateView):
    '''スタッフの表示を行なうページ'''
    model = User
    template_name = 'register/staff_index.html'

    def get_context_data(self, **kwargs):
        context =  generic.TemplateView.get_context_data(self, **kwargs)
        context['users'] = User.objects.all()
        return context

class StaffDelete(OnlySuperuser, generic.DeleteView):
    '''メール送信ページ'''
    model = User
    form_class = UserUpdateForm
    template_name = 'register/staff_delete.html'
    success_url = reverse_lazy('register:staff_index')


class UserDetail(OnlyYouMixin, generic.DetailView):
    """ユーザーの詳細ページ"""
    model = User
    template_name = 'register/user_detail.html'  # デフォルトユーザーを使う場合に備え、きちんとtemplate名を書く


class UserUpdate(OnlyYouMixin, generic.UpdateView):
    """ユーザー情報更新ページ"""
    model = User
    form_class = UserUpdateForm
    template_name = 'register/user_form.html'  # デフォルトユーザーを使う場合に備え、きちんとtemplate名を書く

    def get_success_url(self):
        return resolve_url('register:user_detail', pk=self.kwargs['pk'])


class PasswordChange(PasswordChangeView):
    """パスワード変更ビュー"""
    form_class = MyPasswordChangeForm
    success_url = reverse_lazy('register:password_change_done')
    template_name = 'register/password_change.html'


class PasswordChangeDone(PasswordChangeDoneView):
    """パスワード変更しました"""
    template_name = 'register/password_change_done.html'


class PasswordReset(PasswordResetView):
    """パスワード変更用URLの送付ページ"""
    subject_template_name = 'register/mail_template/password_reset/subject.txt'
    email_template_name = 'register/mail_template/password_reset/message.txt'
    template_name = 'register/password_reset_form.html'
    form_class = MyPasswordResetForm
    success_url = reverse_lazy('register:password_reset_done')


class PasswordResetDone(PasswordResetDoneView):
    """パスワード変更用URLを送りましたページ"""
    template_name = 'register/password_reset_done.html'


class PasswordResetConfirm(PasswordResetConfirmView):
    """新パスワード入力ページ"""
    form_class = MySetPasswordForm
    success_url = reverse_lazy('register:password_reset_complete')
    template_name = 'register/password_reset_confirm.html'


class PasswordResetComplete(PasswordResetCompleteView):
    """新パスワード設定しましたページ"""
    template_name = 'register/password_reset_complete.html'




class MyCalendar(MonthCalendarMixin, WeekWithScheduleMixin, generic.CreateView):
    """月間カレンダー、週間カレンダー、スケジュール登録画面のある欲張りビュー"""
    template_name = 'register/mycalendar.html'
    form_class = BS4ScheduleForm

    def get_context_data(self, **kwargs):
        user = self.request.user
        
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        day = self.kwargs.get('day')
        if month and year and day:
            date = datetime.date(year=int(year), month=int(month), day=int(day))
        else:
            date = datetime.date.today()

register/templates/register/base.html
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <title>レストラン勤務計画管理システム</title>
</head>
<body>
    <!-- ナビバー -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'register:top' %}">勤務管理サイト</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated %} <!-- ユーザがログインしている場合以下を表示 -->
          <li>
            <a class="nav-item nav-link" href="{% url 'register:mycalendar' %}">シフト表の登録</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'register:month_with_schedule' %}">シフト状況</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'register:user_detail' user.pk %}">ユーザー情報閲覧</a> <!-- タブ表示されていく -->
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'register:user_update' user.pk %}">ユーザー情報更新</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'register:logout' %}">ログアウト</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'register:password_change' %}">パスワードの変更</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'register:management' %}">管理用ページ</a>
          </li>
          {% else %} <!-- ユーザがログインしていない場合はこちら -->
          <li class="nav-item">
            <a class="nav-item nav-link" href="{% url 'register:login' %}"> <!-- register の urls.py の login への遷移 -->
            ようこそ、ゲスト！ログインはこちら 
          </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <!-- メインコンテント -->
    <div class="container mt-3">
        {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"></script>
</body>
</html>

register/templates/register/decision_numbers.html
{% extends "register/base.html" %}
{% block content %}
<p> シフトの人数を変更する画面（仮）</p>
{% endblock %}

register/templates/register/login.html
{% extends "register/base.html" %}
{% block content %}
<div class="row">
    <!-- 左側、ログインエリア -->
    <div class="card col-md-6">
        <div class="card-body">
            <form action="{% url 'register:login' %}" method="POST">
                {{ form.non_field_errors }}
                {% for field in form %}
                    {{ field }}
                    {{ field.errors }}
                    <hr>
                {% endfor %}
                <button type="submit" class="btn btn-success btn-lg btn-block" >ログイン</button>
                <input type="hidden" name="next" value="{{ next }}" />
                {% csrf_token %}
            </form>
        </div>
    </div><!-- 左側、ログインエリアおわり -->

    <!-- 右側、会員登録エリア -->
    <div class="card col-md-6">
        <div class="card-body">
            <a href="{% url 'register:user_create' %}" class="btn btn-success btn-lg btn-block" >会員登録</a><hr>
            <a href="{% url 'register:password_reset' %}" class="btn btn-success btn-lg btn-block" >パスワードを忘れた方</a>
        </div>
    </div><!-- 右側、会員登録エリアおわり -->
</div>
{% endblock %}

register/templates/register/month_with_schedule.html
{% extends 'register/base_calendar.html' %}
{% block content %}
<script>
</script>
<style>
	table {
        table-layout: fixed;
    }
    td > div {
      height: 100px;
      overflow: auto;
      white-space: nowrap;
    }

    .btn_noon{
      border-radius: 5px;
      border-color: orangered;
      color: navy;
      background-color: darkorange;
      font-family: "メイリオ", sans-serif;
    }

    .btn_night{
      border-radius: 5px;
      border-color:darkblue;
      color: white;
      background-color: blue;
      font-family: "メイリオ", sans-serif;
    }

</style>

<a href="{% url 'register:month_with_schedule' month.previous.year month.previous.month %}">前月</a>
{{ month.current | date:"Y年m月" }}
<a href="{% url 'register:month_with_schedule' month.next.year month.next.month %}">次月</a>
<table class="table">
  <thead>
    <tr>
      {% for w in month.week_names %}
        <th>{{ w }}</th>
      {% endfor %}
    </tr>
  </thead>
  <tbody>

    {% for week in month.days %}
      <tr>


        {% for day, schedules, decisions in week %}

          {% if month.now == day %}
            <td class = "table-success">

          {% else %}
          	<td id = "{{day}}">

          	<script>

            var noon = 0;
            var night = 0;

            var decision_noon = 0;
            var decision_night = 0;

            {% for s in schedules %}
            	{% if s.start_time >= s.night_start_time %}
            		night++;
            	{% else %}
            		noon++;
            	{% endif %}
            {% endfor %}

            {% for decision in decisions %}
            	{% if forloop.last %}
                	decision_noon = {{ decision.noon_numbers }};
                	decision_night = {{ decision.night_numbers }};
                {% endif %}
     		{% endfor %}

			var year = {{day.year}} // 対象の年
			var month = {{day.month}} // 対象の月
			var day = {{day.day}} // 対象の日

			if({{month.now.year}} <= year && {{month.now.month}} <= month){
			 if({{month.now.month}} < month || {{month.now.day}} < day){

				if(decision_noon > noon || decision_night > night)
            		document.getElementById("{{day}}").className = "table-danger";

				}
			}

            </script>

          {% endif %}


          <div>
            {% if month.current.month != day.month %}
              {{ day | date:"m/d" }}
            {% else %}
              {{ day.day }}

            {% endif %}



 {% for s in schedules %}
 <br>
                           <!-- 1.モーダル表示のためのボタン -->
                           <!--昼シフトと夜シフトを判別-->
{% if s.start_time >= s.night_start_time%}
<button class="btn_night" data-toggle="modal" data-target="#{{s.id}}">
   {{ s.user_name }}
</button>
{% else %}
<button class="btn_noon"  data-toggle="modal" data-target="#{{s.id}}">
   {{ s.user_name }}
</button>
{% endif %}
<!-- 2.モーダルの配置 -->
<div class="modal" id="{{s.id}}" tabindex="-1">
    <div class="modal-dialog">

        <!-- 3.モーダルのコンテンツ -->
        <div class="modal-content">
            <!-- 4.モーダルのヘッダ -->
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="modal-label">
                  <!--各スケジュール記入者に後で変更-->
         {{ day | date:"m/d" }}<br>
          {{s.user_name}}の詳細
                  </h4>
            </div>
            <!-- 5.モーダルのボディ -->
            <div class="modal-body">
               <p> {{ s.user_name }}</p>
               <p>{{ s.summary }}</p>
               <p> {{ s.start_time }} - {{ s.end_time }}</p>
            </div>
            <!-- 6.モーダルのフッタ -->
            <div class="modal-footer">
              <!--削除ボタンを設置 -->
              {% if superuser %}
<form method="GET" action="{% url 'register:delete_m' s.id%}" >
    {% csrf_token %}
    <input type="hidden" name="date" value="{{day.day}}">
    <input type="submit" class ="btn btn-danger"name ="delete_button"value="削除" onclick='return confirm("本当に削除しますか？");'>
</form>
{% endif %}
                <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
            </div>
          </div>
        </div>
    </div>
    </br>
     {% endfor %}





</div>
          </td>

        {% endfor %}
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

register/templates/register/staff_index.html
{% extends "register/base.html" %}
{% block content %}
<font size = "4">
	<li>
		<p>全スタッフ一覧 </p>
	</li>
</font>
{%for user in users %}
<table class="table table-hover">
    <tbody>
        <tr class="clickable" data-toggle="collapse" href="#table-collapse{{user}}" aria-expanded="false" aria-controls="table-collapse{{user}}">
            <th>ユーザー名</th>
            <span class="align-middle">
            <td>{{ user.username }}</td>
            </span>
        </tr>
    </tbody>
	<tbody class="collapse" id="table-collapse{{user}}">
		<tr>
			<th>E-mail</th>
			<td>{{ user.email }}</td>
		</tr>
		<tr>
			<th>姓</th>
			<td>{{ user.last_name }}</td>
		</tr>
		<tr>
			<th>名</th>
			<td>{{ user.first_name }}</td>
		</tr>
		<tr>
			<th></th>
			<td class="btn-toolbar float-right" role="toolbar">
				<div class="btn-group mr-2">
				<a class="btn btn-primary" type="button" href="{% url 'register:user_update' user.pk %}">編集</a>
				</div>
				<div class="btn-group">
				<a class="btn btn-danger" type="button" href="{% url 'register:staff_delete' user.pk %}">削除</a>
				</div>
			</td>
    </tbody>
</table>
<br>
{% endfor %}
	<font size = "4">
		<li>
			<a class="nav-item nav-link" href="{% url 'register:user_create' %}">ユーザの追加</a>
		</li>
	</font>
{% endblock %}